function osmTable(pContainer) {
  this.container = pContainer;
  this.value = "";
  
  //showing
  this.showIDs = true;
  this.showType = true;
  this.columns = [] //and attributes
  this.autoColumns = true; //if true, columns are auto-generated by the data whenever the data updates.
  
  this.setValue = function setValue(data) {
    this.value = data;
    this.generateTable();
  }
  
  this.generateTable = function generateTable() {
    this.container.innerHTML = "";
    
    var $theTable = $(this.container).append("<table/>");
    //generate headers:
    $theHeaders = $theTable.append("<tr/>");
    if (this.showIDs) {
      $theIDs = $theHeaders.append("<th>id</th>");
    }
    if (this.showType) {
      $($theHeaders).append("<th>type</th>");
    }
    
    if(!this.columns) {
      console.debug("initializing columns");
      this.columns = [];
    }
    
    //theContent, containing the individual lines as an array:
    $theContent = [];
    $xmlDoc = $.parseXML(this.value);
    $i = 0;
    var myOsmTable = this;
    $($xmlDoc).find("osm").children().each(function(index, node) {
      //we don't need the index, but the content only:
      if ((node.nodeName == "node") || (node.nodeName == "way") || (node.nodeName == "relation")) {
        $nextElement = new Object();
        $nextElement.id = $(node).attr("id");
        $nextElement.type = node.nodeName;
        $nextElement.attributes = [];
        //now let's parse the attributes:
        $(node).children().each(function(index, tag) {
          if (tag.nodeName == "tag") {
            var k = $(tag).attr("k");
            var v = $(tag).attr("v");
            $nextElement.attributes[k] = v;
            
            //let's collect all keys that occur:
            if ($.inArray(k, myOsmTable.columns) == -1) {
              myOsmTable.columns[myOsmTable.columns.length] = k;
            }
          }
        });
        $theContent[$i] = $nextElement;
        $i++;
      }
    });

    if (this.autoColumns) {
      //for each column generate a th in the header
      $(this.columns).each(function(i, v) {
        $($theHeaders).append("<th>"+v+"</th>");
      });
      //for each content element create the corresponding table row:
      $($theContent).each(function(i,v) {
        var $theRow = $($theTable).append("<tr/>");
        var $o = v;
        if (myOsmTable.showIDs) {
          $($theRow).append("<td>"+v.id+"</td>");
        }
        if (myOsmTable.showType) {
          $($theRow).append("<td>"+v.type+"</td>");
        }
        $(myOsmTable.columns).each(function(i,v) {
          $($theRow).append("<td>"+($o.attributes[v]?$o.attributes[v]:"")+"</td>");
        });
      });
    }
    else {
      console.debug("non-automatic Columns are not supported yet");
    }
    //add the table to the container:
    $(this.container).append($theTable);
  }

  return;
}
