examples = {
  "Drinking Water":{"overpass":"<!--\nThis is an example Overpass query.\nTry it out by pressing the Run button above!\nYou can find more examples with the Load tool.\n-->\n<query type=\"node\">\n  <has-kv k=\"amenity\" v=\"drinking_water\"/>\n  <bbox-query/><!--this is auto-completed with the\n                   current map view coordinates.-->\n</query>\n<print/>"},
  "Drinking Water (Overpass QL)":{"overpass":"/*\nThis is the drinking water example in OverpassQL.\n*/\n(\n  node\n    [\"amenity\"=\"drinking_water\"]\n    (bbox) /* this is auto-completed with the\n              current map view coordinates. */\n);\nout;"},
  "Cycle Network":{"overpass":"<!--\nThis shows the whole cycleway and cycleroute network.\n-->\n<osm-script output=\"json\">\n  <!-- get cycle route relations -->\n  <query type=\"relation\" into=\"cr\">\n    <bbox-query/>\n    <has-kv k=\"route\" v=\"bicycle\"/>\n  </query>\n  <!-- get cycleways (tagging scheme 1) -->\n  <query type=\"way\" into=\"cw1\">\n    <bbox-query/>\n    <has-kv k=\"highway\" v=\"cycleway\"/>\n  </query>\n  <!-- get cycleways (tagging scheme 2) -->\n  <query type=\"way\" into=\"cw2\">\n    <bbox-query/>\n    <has-kv k=\"highway\" v=\"path\"/>\n    <has-kv k=\"bicycle\" v=\"designated\"/>\n  </query>\n  <!-- combine all found cycleways -->\n  <union into=\"cw\">\n    <item set=\"cw1\"/>\n    <item set=\"cw2\"/>\n  </union>\n  <!-- combine with the cycle routes and use recurse to get to underlying geometry (ways and nodes): -->\n  <union>\n    <item set=\"cr\"/>\n    <recurse from=\"cr\" type=\"down\"/>\n    <item set=\"cw\"/>\n    <recurse from=\"cw\" type=\"down\"/>\n  </union>\n  <!-- show the result -->\n  <print mode=\"body\" order=\"quadtile\"/>\n</osm-script>"},
  "List Areas":{"overpass":"<!--\nThis lists all areas which include the map center point.\n-->\n<osm-script output=\"json\">\n  <coord-query/><!--this this is auto-completed with the\n                    current map center coordinates.-->\n  <print/>\n</osm-script>"},
  "Mountains in Area":{"overpass":"<!--\nThis shows all mountains (peaks) in the Dolomites.\nYou may want to use the \"zoom onto data\" button. =>\n-->\n<osm-script output=\"json\">\n  <!-- get all peaks in the area -->\n  <query type=\"node\">\n    <area-query ref=\"3602139488\"/><!-- This is the area-ID for the Dolomites-->\n    <has-kv k=\"natural\" v=\"peak\"/>\n  </query>\n  <print mode=\"body\" order=\"quadtile\"/>\n  <!-- additionally, show the outline of the area -->\n  <union>\n    <id-query type=\"relation\" ref=\"2139488\"/>\n    <recurse type=\"down\"/>\n  </union>\n  <print mode=\"body\" order=\"quadtile\"/>\n</osm-script>"},
  "Map Call":{"overpass":"<!--\nThis is a simple map call.\nIt returns all data in the bounding box.\n-->\n<osm-script output=\"xml\">\n  <union into=\"_\">\n    <bbox-query/>\n    <recurse type=\"up\"/>\n  </union>\n  <print mode=\"meta\" order=\"quadtile\"/>\n</osm-script>"},
};
examples_initial_example = "Drinking Water";
